### ISSUE TITLE
能否增加一个更新环境变量后自动启动，我看更新后还是禁用状态

### ISSUE THREAD

**Issue by linyi81953221** [icepage/AutoUpdateJdCookie#1]
能否增加一个更新环境变量后自动启动，我看更新后还是禁用状态

**Comment by xujinhui2015** [comment]
确实2，还有就是用账号密码不是很方便，经常抢占我的青龙后台的登录，能否改成Client ID和Client Secret的api调用方式来处理阿？

**Comment by icepage** [comment]
> 能否增加一个更新环境变量后自动启动，我看更新后还是禁用状态

更新后，会自动切换成启用状态的，你的青龙版本是多少？

**Comment by icepage** [comment]
> 确实2，还有就是用账号密码不是很方便，经常抢占我的青龙后台的登录，能否改成Client ID和Client Secret的api调用方式来处理阿？

你这个Client ID和Client Secret建议很好，我之前并没想到，等我有空时研究后回复你

**Comment by icepage** [comment]
> > 确实2，还有就是用账号密码不是很方便，经常抢占我的青龙后台的登录，能否改成Client ID和Client Secret的api调用方式来处理阿？
> 
> 你这个Client ID和Client Secret建议很好，我之前并没想到，等我有空时研究后回复你

https://github.com/icepage/AutoUpdateJdCookie/commit/db901f34461659650b26e1777bfc6cb10756268a，已提交完善了

**Comment by icepage** [comment]
> > 确实2，还有就是用账号密码不是很方便，经常抢占我的青龙后台的登录，能否改成Client ID和Client Secret的api调用方式来处理阿？
> 
> 你这个Client ID和Client Secret建议很好，我之前并没想到，等我有空时研究后回复你

https://github.com/icepage/AutoUpdateJdCookie/commit/db901f34461659650b26e1777bfc6cb10756268a

**Comment by icepage** [comment]
> > 确实2，还有就是用账号密码不是很方便，经常抢占我的青龙后台的登录，能否改成Client ID和Client Secret的api调用方式来处理阿？
> 
> 你这个Client ID和Client Secret建议很好，我之前并没想到，等我有空时研究后回复你

已优化了，分支如下：
https://github.com/icepage/AutoUpdateJdCookie/commit/db901f34461659650b26e1777bfc6cb10756268a

**Comment by cdrlover126** [comment]
在青龙2.16.4版本下的在更新后不能自动启动，还是需要手动设置启用

**Comment by icepage** [comment]
> 在青龙2.16.4版本下的在更新后不能自动启动，还是需要手动设置启用

https://github.com/icepage/AutoUpdateJdCookie/commit/6d70fe03a39f49aeb7464cfae803e695cfdd5fbc
加上了更新后启用的逻辑

**Comment by linyi81953221** [comment]
感谢大神分享

**Comment by uwhatsup** [comment]
OpenApi使用指南

1. 在系统设置 -> 应用设置 -> 添加应用，权限目前支持5个模块，可以选择多个模块。选择一个模块之后，可读写此模块的所有接口。
2. 使用生成的 client_id 和 client_secret 请求获取token接口 http://localhost:5700/open/auth/token?client_id=xxxxxx&client_secret=xxxxxxxx
3. 上面接口返回的token有效期为30天，可用于请求青龙的接口 curl 'http://localhost:5700/open/envs?searchValue=&t=1630032278171' -H 'Authorization: Bearer 接口返回的token'
4. openapi的接口与系统正常接口的区别就是青龙里的是/api/envs，openapi是/open/envs，即就是青龙接口中的api换成open
6. 此功能支持青龙2.9+，更新时需要执行一次ql check

**Comment by xujinhui2015** [comment]
对的，我就是想这么处理，大佬用token的方式实现也是只解决了一部分，这个token也会失效。如果用Client ID和Client Secret的api调用方式，就永远不会失效了，也不会抢占登录面板。

**Comment by icepage** [comment]
> OpenApi使用指南
> 
> 1. 在系统设置 -> 应用设置 -> 添加应用，权限目前支持5个模块，可以选择多个模块。选择一个模块之后，可读写此模块的所有接口。
> 2. 使用生成的 client_id 和 client_secret 请求获取token接口 http://localhost:5700/open/auth/token?client_id=xxxxxx&client_secret=xxxxxxxx
> 3. 上面接口返回的token有效期为30天，可用于请求青龙的接口 curl 'http://localhost:5700/open/envs?searchValue=&t=1630032278171' -H 'Authorization: Bearer 接口返回的token'
> 4. openapi的接口与系统正常接口的区别就是青龙里的是/api/envs，openapi是/open/envs，即就是青龙接口中的api换成open
> 5. 此功能支持青龙2.9+，更新时需要执行一次ql check

了解了，这块我看下接入

**Comment by icepage** [comment]
[d7163da3b84808796990a6e905c9bc6bdf2c3284](https://github.com/icepage/AutoUpdateJdCookie/commit/d7163da3b84808796990a6e905c9bc6bdf2c3284)，更新了可用client_id和client_secret登录
