### ISSUE TITLE
JD新增了验证方式

### ISSUE THREAD

**Issue by kfg81** [icepage/AutoUpdateJdCookie#13]
今天发现JD新增了汉字的验证方式，如下图，脚本跑了几次都没有成功通过，大佬要是方便的话，麻烦更新，非常感谢。

![9bef12c3be0acd23ff0434d4c8b62da](https://github.com/icepage/AutoUpdateJdCookie/assets/12681019/6d26ad43-aefa-42fc-996a-8430bdc2af5c)

**Comment by xiaomo2002** [comment]
滑块也过不了了 你们的正常吗

**Comment by icepage** [comment]
> 今天发现JD新增了汉字的验证方式，如下图，脚本跑了几次都没有成功通过，大佬要是方便的话，麻烦更新，非常感谢。
> 
> ![9bef12c3be0acd23ff0434d4c8b62da](https://private-user-images.githubusercontent.com/12681019/345239304-6d26ad43-aefa-42fc-996a-8430bdc2af5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyMzcyODIsIm5iZiI6MTcyMDIzNjk4MiwicGF0aCI6Ii8xMjY4MTAxOS8zNDUyMzkzMDQtNmQyNmFkNDMtYWVmYS00MmZjLTk5NmEtODQzMGJkYzJhZjVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA2VDAzMzYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhMGFkM2FjYzI1Mjk2NzczZDNkZDU2ZjQxNDJjMTNjY2JjZDQwMGE1NjRlYmJjOGRjZjJiYzlmODUyOTM5ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bwBxcLOyLWBkasKFvQGrnJiwgkWTT6UVQFmhX2-T9KE)

https://github.com/icepage/AutoUpdateJdCookie/commit/b263e5509be18ddad1bea82652e5cedf1ba93ea1  
你好，已做了点选支持，希望可以帮助到你。

**Comment by icepage** [comment]
> 滑块也过不了了 你们的正常吗

可否描述下过不了的具体情况？

**Comment by xiaomo2002** [comment]
> > 滑块也过不了了 你们的正常吗
> 
> 
> 
> 可否描述下过不了的具体情况？

位置对的 但是应该检测到非正常滑动

**Comment by xiaomo2002** [comment]
> > > > 滑块也过不了了 你们的正常吗
> 
> > > 
> 
> > > 
> 
> > > 可否描述下过不了的具体情况？
> 
> > 
> 
> > 位置对的 但是应该检测到非正常滑动
> 
> 
> 
> 你的问题与  https://github.com/icepage/AutoUpdateJdCookie/issues/7 这个问题类似。因为我这边没法复现，所以不知怎么修复问题。可能与号有关，或者可以使用其它项目尝试一下。

作者可以参考svjdck的滑块项目，不是号的问题，和其他人交流应该是模块问题。如果有需要 我可以远程提供复现

**Comment by icepage** [comment]
> > > > > 滑块也过不了了 你们的正常吗
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 可否描述下过不了的具体情况？
> > 
> > 
> > > 
> > 
> > 
> > > 位置对的 但是应该检测到非正常滑动
> > 
> > 
> > 你的问题与  #7 这个问题类似。因为我这边没法复现，所以不知怎么修复问题。可能与号有关，或者可以使用其它项目尝试一下。
> 
> 作者可以参考svjdck的滑块项目，不是号的问题，和其他人交流应该是模块问题。如果有需要 我可以远程提供复现

https://github.com/icepage/AutoUpdateJdCookie/commit/03464614a836414f725b3b41bd84f54bd22b1c58 ，我参考svjdck，作了滑块验证的调整，你可以尝试下，希望可以帮助到你。

**Comment by xiaomo2002** [comment]
已测试 还是不行。看了下滑块速度过快，对准没有设置随机偏移，可以参考试试。感谢作者

不过目前滑块数比较少，估计京东会放弃滑块


吃橘子?的猫
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "icepage/AutoUpdateJdCookie"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月7日(星期天) 晚上10:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [icepage/AutoUpdateJdCookie] JD新增了验证方式 (Issue #13)





      
滑块也过不了了 你们的正常吗
              
可否描述下过不了的具体情况？
      
位置对的 但是应该检测到非正常滑动
  
你的问题与  #7 这个问题类似。因为我这边没法复现，所以不知怎么修复问题。可能与号有关，或者可以使用其它项目尝试一下。
  
作者可以参考svjdck的滑块项目，不是号的问题，和其他人交流应该是模块问题。如果有需要 我可以远程提供复现
  
0346461 ，我参考svjdck，作了滑块验证的调整，你可以尝试下，希望可以帮助到你。

**Comment by icepage** [comment]
> 已测试 还是不行。看了下滑块速度过快，对准没有设置随机偏移，可以参考试试。感谢作者 不过目前滑块数比较少，估计京东会放弃滑块 吃橘子?的猫 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "icepage/AutoUpdateJdCookie" ***@***.***&gt;; 发送时间:&nbsp;2024年7月7日(星期天) 晚上10:45 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [icepage/AutoUpdateJdCookie] JD新增了验证方式 (Issue #13) 滑块也过不了了 你们的正常吗 可否描述下过不了的具体情况？ 位置对的 但是应该检测到非正常滑动 你的问题与 #7 这个问题类似。因为我这边没法复现，所以不知怎么修复问题。可能与号有关，或者可以使用其它项目尝试一下。 作者可以参考svjdck的滑块项目，不是号的问题，和其他人交流应该是模块问题。如果有需要 我可以远程提供复现 [0346461](https://github.com/icepage/AutoUpdateJdCookie/commit/03464614a836414f725b3b41bd84f54bd22b1c58) ，我参考svjdck，作了滑块验证的调整，你可以尝试下，希望可以帮助到你。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

滑块速度是对齐了svjdck的速度调整的，准确度上高了不少。没有对准是否调整下slide_difference偏移量试下？还会出现位置对的 但是应该检测到非正常滑动这种情况吗？

**Comment by xiaomo2002** [comment]
调整对齐了&nbsp; 应该是检测到非正常滑动问题&nbsp;


吃橘子?的猫
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月9日(星期二) 中午12:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [icepage/AutoUpdateJdCookie] JD新增了验证方式 (Issue #13)














  
已测试 还是不行。看了下滑块速度过快，对准没有设置随机偏移，可以参考试试。感谢作者 不过目前滑块数比较少，估计京东会放弃滑块 吃橘子?的猫 @.*** &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "icepage/AutoUpdateJdCookie" @.&gt;; 发送时间:&nbsp;2024年7月7日(星期天) 晚上10:45 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [icepage/AutoUpdateJdCookie] JD新增了验证方式 (Issue #13) 滑块也过不了了 你们的正常吗 可否描述下过不了的具体情况？ 位置对的 但是应该检测到非正常滑动 你的问题与 #7 这个问题类似。因为我这边没法复现，所以不知怎么修复问题。可能与号有关，或者可以使用其它项目尝试一下。 作者可以参考svjdck的滑块项目，不是号的问题，和其他人交流应该是模块问题。如果有需要 我可以远程提供复现 0346461 ，我参考svjdck，作了滑块验证的调整，你可以尝试下，希望可以帮助到你。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
滑块速度是对齐了svjdck的速度调整的，准确度上高了不少。没有对准是否调整下slide_difference偏移量试下？还会出现位置对的 但是应该检测到非正常滑动这种情况吗？

**Comment by icepage** [comment]
> 调整对齐了&nbsp; 应该是检测到非正常滑动问题&nbsp; 吃橘子?的猫 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年7月9日(星期二) 中午12:04 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [icepage/AutoUpdateJdCookie] JD新增了验证方式 (Issue #13) 已测试 还是不行。看了下滑块速度过快，对准没有设置随机偏移，可以参考试试。感谢作者 不过目前滑块数比较少，估计京东会放弃滑块 吃橘子?的猫 @.*** &nbsp; … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "icepage/AutoUpdateJdCookie" @.&gt;; 发送时间:&nbsp;2024年7月7日(星期天) 晚上10:45 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [icepage/AutoUpdateJdCookie] JD新增了验证方式 (Issue #13) 滑块也过不了了 你们的正常吗 可否描述下过不了的具体情况？ 位置对的 但是应该检测到非正常滑动 你的问题与 #7 这个问题类似。因为我这边没法复现，所以不知怎么修复问题。可能与号有关，或者可以使用其它项目尝试一下。 作者可以参考svjdck的滑块项目，不是号的问题，和其他人交流应该是模块问题。如果有需要 我可以远程提供复现 [0346461](https://github.com/icepage/AutoUpdateJdCookie/commit/03464614a836414f725b3b41bd84f54bd22b1c58) ，我参考svjdck，作了滑块验证的调整，你可以尝试下，希望可以帮助到你。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt; 滑块速度是对齐了svjdck的速度调整的，准确度上高了不少。没有对准是否调整下slide_difference偏移量试下？还会出现位置对的 但是应该检测到非正常滑动这种情况吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

好吧，可能是与模块相关了

**Comment by kfg81** [comment]
> > 今天发现JD新增了汉字的验证方式，如下图，脚本跑了几次都没有成功通过，大佬要是方便的话，麻烦更新，非常感谢。
> > ![9bef12c3be0acd23ff0434d4c8b62da](https://private-user-images.githubusercontent.com/12681019/345239304-6d26ad43-aefa-42fc-996a-8430bdc2af5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyMzcyODIsIm5iZiI6MTcyMDIzNjk4MiwicGF0aCI6Ii8xMjY4MTAxOS8zNDUyMzkzMDQtNmQyNmFkNDMtYWVmYS00MmZjLTk5NmEtODQzMGJkYzJhZjVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA2VDAzMzYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhMGFkM2FjYzI1Mjk2NzczZDNkZDU2ZjQxNDJjMTNjY2JjZDQwMGE1NjRlYmJjOGRjZjJiYzlmODUyOTM5ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bwBxcLOyLWBkasKFvQGrnJiwgkWTT6UVQFmhX2-T9KE)
> 
> [b263e55](https://github.com/icepage/AutoUpdateJdCookie/commit/b263e5509be18ddad1bea82652e5cedf1ba93ea1) 你好，已做了点选支持，希望可以帮助到你。

大佬，经测试，能正常点选了，谢谢！！

**Comment by kfg81** [comment]
大佬，今天发现点选汉字，重试了20多次一直都是失败。

**Comment by icepage** [comment]
> 大佬，今天发现点选汉字，重试了20多次一直都是失败。

https://github.com/icepage/AutoUpdateJdCookie/commit/f48ce81d6e566edd3830b10b31b88c526dd9a787    修复了刷新问题了，希望可以帮助到你
