### ISSUE TITLE
点选增加了很多新的

### ISSUE THREAD

**Issue by xiaomo2002** [icepage/AutoUpdateJdCookie#15]
点选增加了很多新的，导致容易超时失败。作者可以同步更新下吗，如果可以的话可以对接个第三方打码识别接口

**Comment by kfg81** [comment]
遇到同样的问题，汉字点选多了很多，无法识别。重试了20多次都不行

**Comment by xiaomo2002** [comment]
点选 不能刷新了

**Comment by icepage** [comment]
> 点选 不能刷新了

https://github.com/icepage/AutoUpdateJdCookie/commit/f48ce81d6e566edd3830b10b31b88c526dd9a787     修复了刷新问题了
