### ISSUE TITLE
新版本不知道为啥到了输入验证码的那界面就会崩溃退出

### ISSUE THREAD

**Issue by 5jwoj** [icepage/AutoUpdateJdCookie#18]
由于是闪退，所以没法提供日志，即使是把sms_func设置为no，程序还是会闪退
还有个问题是有些账号，即使是输入正常的账号和密码，京东依旧提示账密错误，过几个小时以后，又可以登录上。

**Comment by icepage** [comment]
不太明白闪退的打开方式，你是直接双击点开main.py然后闪退的吗？还是在终端运行后闪退的？京东提示账密错误这种情况，我没

**Comment by icepage** [comment]
不太明白闪退的打开方式，你是直接双击点开main.py然后闪退的吗？还是在终端运行后闪退的？京东提示账密错误这种情况，我没遇到过。
