### ISSUE TITLE
有个思路，不知道能实现不

### ISSUE THREAD

**Issue by tomatochaoegg** [icepage/AutoUpdateJdCookie#19]
部署个docker容器，定时扫描青龙的环境变量，发现jdcookie失效，就自动用设置的账号密码登录，实现无感知更新cookie；

**Comment by Smithcaige** [comment]
可以啊，当你的ck失效时，青龙脚本中有个会给你设置成禁用，这时候你去获取status =1的就行了，但是问题是怎么实现自动获取验证码，这个webhook不是只能做接收通知吗，他支持双向吗

**Comment by icepage** [comment]
> 部署个docker容器，定时扫描青龙的环境变量，发现jdcookie失效，就自动用设置的账号密码登录，实现无感知更新cookie；

部署个docker容器  -->  可自行编写;
定时扫描青龙的环境变量  -->   青龙的CK脚本实现;
发现jdcookie失效，就自动用设置的账号密码登录，实现无感知更新cookie -->  本定时脚本实现。

如果要做成CK检测失效后 串行触发更新的，可以参考https://github.com/icepage/AutoUpdateJdCookie/issues/17这个issue， 希望可以帮助到你！

**Comment by icepage** [comment]
> 可以啊，当你的ck失效时，青龙脚本中有个会给你设置成禁用，这时候你去获取status =1的就行了，但是问题是怎么实现自动获取验证码，这个webhook不是只能做接收通知吗，他支持双向吗

本应用调用短信验证码的webhook是单向的，但是短信验证码的webhook应用可以是双向的，可以参考 https://github.com/icepage/SmsCodeWebhook  这个项目

**Comment by OwnerCM** [comment]
有没有编写docker的大佬开放

**Comment by Tyrone2333** [comment]
我已经在群晖跑了 3 周, 里面运行 schedule_main.py 半小时扫描一次, dockerfile 提交到仓库了, 等作者构建到 hub 吧 @OwnerCM @tomatochaoegg

**Comment by icepage** [comment]
https://github.com/icepage/AutoUpdateJdCookie/commit/534611aa957432821a53d9cb6acb65d939a3f60d    
 镜像已上传hub，docker部署已支持，感谢 @Tyrone2333 大佬的dockerfile

**Comment by Jioani** [comment]
> 我已经在群晖跑了 3 周, 里面运行 schedule_main.py 半小时扫描一次, dockerfile 提交到仓库了, 等作者构建到 hub 吧 @OwnerCM @tomatochaoegg

感谢大佬
