### ISSUE TITLE
请问可以在青龙面板中定时运行，以实现自动更新cookie吗？

### ISSUE THREAD

**Issue by cdrlover126** [icepage/AutoUpdateJdCookie#2]
赞一个！请问可以在青龙面板中定时运行，以实现自动更新cookie吗？

**Comment by icepage** [comment]
> 赞一个！请问可以在青龙面板中定时运行，以实现自动更新cookie吗？

感谢你的赞！！如果你使用的是LINUX系统，playwright是支持LINUX上运行的，你可以在LINUX上跑定时任务来实现。
