### ISSUE TITLE
是否用浏览器无痕窗口更好?

### ISSUE THREAD

**Issue by szdongjun** [icepage/AutoUpdateJdCookie#20]
我发觉最近触发短信越来越频烦了,有可能平时使用代理上网,登录被记录和常登录地不同而被认为风险号?我猜的,不确定,是否用浏览器无痕窗口更好,而且无痕方式不记录,关闭就什么没了,但普通浏览器模式，一般会记录之前登录的信息，就好像我们自己手动在普通浏览器登录，一般如果你直接关闭网页，重新打开的时候还是登陆状态，甚至是关闭浏览器，重新打开也会有，只有按退出这个账号才不会挂在上面

**Comment by icepage** [comment]
本脚本就是使用无痕模式的，页面上不会展示无痕模式的字样，可以ctrl+H确认

**Comment by icepage** [comment]
大概率是号的问题，作者测试过多个号同一机器运行，有些号就是频繁出现短信，有些就一直不会触发
