### ISSUE TITLE
运行报错，能看出原因是啥吗？

### ISSUE THREAD

**Issue by nethawkhu** [icepage/AutoUpdateJdCookie#28]
[36m__main__[0m:[36mrun_scheduled_tasks[0m:[36m25[0m - [1m下次更新任务时间为2024-10-07 11:22:00[0m
-- | -- | --
2024/10/06 11:22:03 | stdout |  
2024/10/06 11:22:03 | stdout | - [pid=20][err] [20:33:1006/112203.239309:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
2024/10/06 11:22:03 | stdout | - [pid=20][err] [20:20:1006/112203.237357:ERROR:env.cc(258)] The platform failed to initialize.  Exiting.
2024/10/06 11:22:03 | stdout | - [pid=20][err] [20:20:1006/112203.237174:ERROR:ozone_platform_x11.cc(244)] Missing X server or $DISPLAY
2024/10/06 11:22:03 | stdout | - <launched> pid=20
2024/10/06 11:22:03 | stdout | <launching> /root/.cache/ms-playwright/chromium-1134/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate,HttpsUpgrades,PaintHolding,PlzDedicatedWorker --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen --unsafely-disable-devtools-self-xss-warnings --no-sandbox --no-sandbox --disable-setuid-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-M0hSaQ --remote-debugging-pipe --no-startup-window
2024/10/06 11:22:03 | stdout | Call log:
2024/10/06 11:22:03 | stdout | ╚════════════════════════════════════════════════════════════════════════════════════════════════╝
2024/10/06 11:22:03 | stdout | ║ <3 Playwright Team                                                                             ║
2024/10/06 11:22:03 | stdout | ║                                                                                                ║
2024/10/06 11:22:03 | stdout | ║ Set either 'headless: true' or use 'xvfb-run <your-playwright-app>' before running Playwright. ║
2024/10/06 11:22:03 | stdout | ║ Looks like you launched a headed browser without having a XServer running.                     ║
2024/10/06 11:22:03 | stdout | ╔════════════════════════════════════════════════════════════════════════════════════════════════╗
2024/10/06 11:22:03 | stdout |  
2024/10/06 11:22:03 | stdout | Browser logs:
2024/10/06 11:22:03 | stdout | playwright._impl._errors.TargetClosedError: BrowserType.launch: Target page, context or browser has been closed
2024/10/06 11:22:03 | stdout | raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
2024/10/06 11:22:03 | stdout | File "/usr/local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 514, in wrap_api_call
2024/10/06 11:22:03 | stdout | return await self._connection.wrap_api_call(
2024/10/06 11:22:03 | stdout | File "/usr/local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 59, in send
2024/10/06 11:22:03 | stdout | Browser, from_channel(await self._channel.send("launch", params))
2024/10/06 11:22:03 | stdout | File "/usr/local/lib/python3.10/site-packages/playwright/_impl/_browser_type.py", line 95, in launch
2024/10/06 11:22:03 | stdout | await self._impl_obj.launch(
2024/10/06 11:22:03 | stdout | File "/usr/local/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 14115, in launch
2024/10/06 11:22:03 | stdout | browser = await playwright.chromium.launch(headless=headless, args=args)
2024/10/06 11:22:03 | stdout | File "/app/main.py", line 370, in get_jd_pt_key
2024/10/06 11:22:03 | stdout | pt_key = await get_jd_pt_key(playwright, user)
2024/10/06 11:22:03 | stdout | File "/app/main.py", line 507, in main
2024/10/06 11:22:03 | stdout | Traceback (most recent call last):
2024/10/06 11:22:03 | stdout | [32m2024-10-06 11:22:03.029[0m \| [1mINFO    [0m \| [36mmain[0m:[36mmain[0m:[36m506[0m - [1m开始更新18916808180[0m
2024/10/06 11:22:02 | stdout | [32m2024-10-06 11:22:02.123[0m \| [1mINFO    [0m \| [36mmain[0m:[36mmain[0m:[36m484[0m - [1m获取环境变量成功[0m
2024/10/06 11:22:01 | stdout | [32m2024-10-06 11:22:01.518[0m \| [1mINFO    [0m \| [36mmain[0m:[36mget_ql_api[0m:[36m444[0m - [1mclient_id和client_secret正常可用......[0m
2024/10/06 11:22:00 | stdout | [32m2024-10-06 11:22:00.395[0m \| [1mINFO    [0m \| [36mmain[0m:[36mget_ql_api[0m:[36m440[0m - [1m使用client_id和client_secret登录......[0m
2024/10/06 11:22:00 | stdout | [32m2024-10-06 11:22:00.394[0m \| [1mINFO    [0m \| [36mmain[0m:[36mget_ql_api[0m:[36m434[0m - [1m开始获取QL登录态......[0m

**Comment by nethawkhu** [comment]
看日志，ql环境已经读取到了，也看到了第一个失效的账号，后面就报错了。

**Comment by icepage** [comment]
config.py里的headless = False要改成headless = True

**Comment by nethawkhu** [comment]
感谢，这个问题解决了。。。然后有新的错误日志，请帮忙看看，谢谢。

2024/10/09 23:35:15 | stdout | [32m2024-10-09 23:35:15.023[0m \| [31m[1mERROR   [0m \| [36mmain[0m:[36mmain[0m:[36m509[0m - [31m[1m获取pt_key失败[0m
-- | -- | --
2024/10/09 23:35:14 | stdout | IndexError: list index out of range
2024/10/09 23:35:14 | stdout | target_char_list = list(re.findall(r'[\u4e00-\u9fff]+', word)[1])
2024/10/09 23:35:14 | stdout | File "/app/main.py", line 205, in auto_shape
2024/10/09 23:35:14 | stdout | await auto_shape(page, retry_times=30)
2024/10/09 23:35:14 | stdout | File "/app/main.py", line 403, in get_jd_pt_key
2024/10/09 23:35:14 | stdout | Traceback (most recent call last):
2024/10/09 23:35:14 | stdout | [32m2024-10-09 23:35:14.906[0m \| [1mINFO    [0m \| [36mmain[0m:[36mauto_shape[0m:[36m203[0m - [1m开始文字识别,点击中......[0m
2024/10/09 23:35:14 | stdout | [32m2024-10-09 23:35:14.150[0m \| [1mINFO    [0m \| [36mmain[0m:[36mauto_shape[0m:[36m134[0m - [1m第2次自动识别形状中...[0m
2024/10/09 23:35:11 | stdout | [32m2024-10-09 23:35:11.989[0m \| [1mINFO    [0m \| [36mmain[0m:[36mauto_shape[0m:[36m244[0m - [1m文字识别失败,刷新中......[0m
2024/10/09 23:35:11 | stdout | [32m2024-10-09 23:35:11.130[0m \| [1mINFO    [0m \| [36mmain[0m:[36mauto_shape[0m:[36m203[0m - [1m开始文字识别,点击中......[0m
2024/10/09 23:35:10 | stdout | [32m2024-10-09 23:35:10.398[0m \| [1mINFO    [0m \| [36mmain[0m:[36mauto_shape[0m:[36m134[0m - [1m第1次自动识别形状中...[0m
2024/10/09 23:35:09 | stdout | [32m2024-10-09 23:35:09.121[0m \| [1mINFO    [0m \| [36mmain[0m:[36mauto_move_slide[0m:[36m79[0m - [1m未找到小图,退出移动滑块[0m
2024/10/09 23:35:06 | stdout | [32m2024-10-09 23:35:06.116[0m \| [1mINFO    [0m \| [36mmain[0m:[36mauto_move_slide[0m:[36m73[0m - [1m第2次尝试自动移动滑块中...[0m
2024/10/09 23:34:58 | stdout | [32m2024-10-09 23:34:58.545[0m \| [1mINFO    [0m \| [36mmain[0m:[36mauto_move_slide[0m:[36m73[0m - [1m第1次尝试自动移动滑块中...[0m
2024/10/09 23:34:49 | stdout | [32m2024-10-09 23:34:49.829[0m \| [1mINFO    [0m \| [36mmain[0m:[36mmain[0m:[36m506[0m - [1m开始更新1360*******[0m

**Comment by nethawkhu** [comment]
还有这种。。。

2024/10/09 19:10:33	stdout	[32m2024-10-09 19:10:33.698[0m | [31m[1mERROR   [0m | [36mmain[0m:[36mmain[0m:[36m509[0m - [31m[1m获取pt_key失败[0m
2024/10/09 19:10:33	stdout	
2024/10/09 19:10:33	stdout	waiting for locator("#msShortcutMenu") to be visible
2024/10/09 19:10:33	stdout	Call log:
2024/10/09 19:10:33	stdout	playwright._impl._errors.TimeoutError: Page.wait_for_selector: Timeout 120000ms exceeded.
2024/10/09 19:10:33	stdout	    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
2024/10/09 19:10:33	stdout	  File "/usr/local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 514, in wrap_api_call
2024/10/09 19:10:33	stdout	    return await self._connection.wrap_api_call(
2024/10/09 19:10:33	stdout	  File "/usr/local/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 59, in send
2024/10/09 19:10:33	stdout	    await self._channel.send("waitForSelector", locals_to_params(locals()))
2024/10/09 19:10:33	stdout	  File "/usr/local/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 323, in wait_for_selector
2024/10/09 19:10:33	stdout	    return await self._main_frame.wait_for_selector(**locals_to_params(locals()))
2024/10/09 19:10:33	stdout	  File "/usr/local/lib/python3.10/site-packages/playwright/_impl/_page.py", line 397, in wait_for_selector
2024/10/09 19:10:33	stdout	    await self._impl_obj.wait_for_selector(
2024/10/09 19:10:33	stdout	  File "/usr/local/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 7999, in wait_for_selector
2024/10/09 19:10:33	stdout	    await page.wait_for_selector('#msShortcutMenu', state='visible', timeout=120000)
2024/10/09 19:10:33	stdout	  File "/app/main.py", line 411, in get_jd_pt_key
2024/10/09 19:10:33	stdout	Traceback (most recent call last):
2024/10/09 19:08:33	stdout	[32m2024-10-09 19:08:33.597[0m | [1mINFO    [0m | [36mmain[0m:[36mget_jd_pt_key[0m:[36m410[0m - [1m等待获取cookie...[0m
2024/10/09 19:08:33	stdout	[32m2024-10-09 19:08:33.586[0m | [1mINFO    [0m | [36mmain[0m:[36msms_recognition[0m:[36m293[0m - [1m开始短信验证码识别[0m
2024/10/09 19:08:32	stdout	[32m2024-10-09 19:08:32.584[0m | [1mINFO    [0m | [36mmain[0m:[36mauto_shape[0m:[36m140[0m - [1m未找到形状图,退出识别状态[0m
2024/10/09 19:08:29	stdout	[32m2024-10-09 19:08:29.580[0m | [1mINFO    [0m | [36mmain[0m:[36mauto_shape[0m:[36m134[0m - [1m第1次自动识别形状中...[0m
2024/10/09 19:08:28	stdout	[32m2024-10-09 19:08:28.275[0m | [1mINFO    [0m | [36mmain[0m:[36mauto_move_slide[0m:[36m79[0m - [1m未找到小图,退出移动滑块[0m
2024/10/09 19:08:25	stdout	[32m2024-10-09 19:08:25.272[0m | [1mINFO    [0m | [36mmain[0m:[36mauto_move_slide[0m:[36m73[0m - [1m第2次尝试自动移动滑块中...[0m
2024/10/09 19:08:18	stdout	[32m2024-10-09 19:08:18.030[0m | [1mINFO    [0m | [36mmain[0m:[36mauto_move_slide[0m:[36m73[0m - [1m第1次尝试自动移动滑块中...[0m
2024/10/09 19:08:08	stdout	[32m2024-10-09 19:08:08.294[0m | [1mINFO    [0m | [36mmain[0m:[36mmain[0m:[36m506[0m - [1m开始更新1891*********[0m

**Comment by icepage** [comment]
IndexError: list index out of range，这里识别点选验证码时出错了，日志看是偶发性的识别不了，这个要做下兼容。重试是必现的吗？ @nethawkhu

**Comment by nethawkhu** [comment]
> IndexError: list index out of range，这里识别点选验证码时出错了，日志看是偶发性的识别不了，这个要做下兼容。重试是必现的吗？ @nethawkhu

不是必现的，我这里的京东账号很多，每次更新几个后就会出现一次，没有什么特别的规律，重新运行后前面出错失败的账号也能成功，所以不是账号的问题。

**Comment by icepage** [comment]
我对IndexError: list index out of range的报错做了兼容，报错时会重新刷新，镜像也更新了 @nethawkhu
