### ISSUE TITLE
二次验证图形的问题

### ISSUE THREAD

**Issue by cdrlover126** [icepage/AutoUpdateJdCookie#3]
当cookie失效时，需要重新登录验证。在滑块验证后，有时会出现二次验证，即问图形形状或选择颜色的方式，请问这种情况能否通过代码解决实现自动验证？

**Comment by icepage** [comment]
目前无破解这种方式的验证码的办法，我也在尝试中。十分抱歉，无法帮到你

**Comment by cdrlover126** [comment]
感谢！期待有突破。发自我的荣耀手机-------- 原始邮件 --------发件人： icepage ***@***.***>日期： 2024年5月14日周二 17:41收件人： icepage/AutoUpdateJdCookie ***@***.***>抄送： cdrlover126 ***@***.***>, Author ***@***.***>主    题： Re: [icepage/AutoUpdateJdCookie] 二次验证图形的问题 (Issue #3)
目前无破解这种方式的验证码的办法，我也在尝试中。十分抱歉，无法帮到你

**Comment by cdrlover126** [comment]
谢谢๑•́₃•̀๑发自我的荣耀手机-------- 原始邮件 --------发件人： xenoscccd ***@***.***>日期： 2024年5月27日周一 16:53收件人： icepage/AutoUpdateJdCookie ***@***.***>抄送： cdrlover126 ***@***.***>, Author ***@***.***>主    题： Re: [icepage/AutoUpdateJdCookie] 二次验证图形的问题 (Issue #3)

目前无破解这种方式的验证码的办法，我也在尝试中。十分抱歉，无法帮到你
大佬，这个二次验证图形的之前有一个京东自动退会项目也用到，已经实现了，但是需要通过OCR的方式来识别。希望这个能提供相关帮助到你
https://github.com/yqchilde/JDMemberCloseAccount

**Comment by icepage** [comment]
> 谢谢๑•́₃•̀๑发自我的荣耀手机-------- 原始邮件 --------发件人： xenoscccd ***@***.***>日期： 2024年5月27日周一 16:53收件人： icepage/AutoUpdateJdCookie ***@***.***>抄送： cdrlover126 ***@***.***>, Author ***@***.***>主 题： Re: [icepage/AutoUpdateJdCookie] 二次验证图形的问题 (Issue #3) 目前无破解这种方式的验证码的办法，我也在尝试中。十分抱歉，无法帮到你 大佬，这个二次验证图形的之前有一个京东自动退会项目也用到，已经实现了，但是需要通过OCR的方式来识别。希望这个能提供相关帮助到你 https://github.com/yqchilde/JDMemberCloseAccount —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

十分感谢你的关注及提供的资料！目前文字识别这块是可以成功的，形状识别这块打算用opencv做识别。但本人目前在投入另外的项目，这块需求暂时可能不会有进度

**Comment by icepage** [comment]
> 当cookie失效时，需要重新登录验证。在滑块验证后，有时会出现二次验证，即问图形形状或选择颜色的方式，请问这种情况能否通过代码解决实现自动验证？

https://github.com/icepage/AutoUpdateJdCookie/commit/84bb57e53ebf2dc8b51ab2da09802434b57d8f8f    二次图形验证已实现。
