### ISSUE TITLE
每次登录都要验证码？

### ISSUE THREAD

**Issue by a65101855** [icepage/AutoUpdateJdCookie#30]

**Comment by icepage** [comment]
登录一定要过滑块验证码，其它如点选或短信验证码非必现

**Comment by icepage** [comment]
加了force_update设置为True时, 即使账号未失效也更新，配置在每个账号下，镜像已更新
    "13500000000": {
        "password": "123456",
        "pt_pin": "123456",
        "sms_func": "webhook",
        "sms_webhook": "https://127.0.0.1:3000/getCode",
        # 设置为True时, 即使账号未失效也更新
        "force_update": True
    },  @nethawkhu 

你提的需求很棒，这个需求也解决了我平时调试需要经常要去禁用失效才能触发的麻烦过程！！

**Comment by nethawkhu** [comment]
再提一个建议。

docker 第一次启动的时候，可以直接先把任务走一次，而不要等定时再执行任务。

**Comment by icepage** [comment]
> 再提一个建议。
> 
> docker 第一次启动的时候，可以直接先把任务走一次，而不要等定时再执行任务。

这个会有一个问题，如果使用的是手动输入短信验证码的话，作为单独任务时是需要分配终端的，用-i运行 ，作为定时任务时是不需要终端的，用-d运行。两者不能混合用
