### ISSUE TITLE
增加登录方式—qq\wx扫码登录

### ISSUE THREAD

**Issue by wdssfff00** [icepage/AutoUpdateJdCookie#39]
只是提一句👀功能建议+已有类似无头项目
1、账密家宽也大量验证码
2、qq账密太敏感
3、且注意：AutoUpdateJdCookie核心还是无感更新ck，不用天天手动验证码
4、所以我明白qq、wx扫码登录的行为还是与3冲突，本提案只是为了隐私且【相对】方便登录
（感觉更适合对接autmna或者无界的插件，qq/wx机器人输出无头截图的二维码，直接长按扫码登录）

![首页](https://github.com/user-attachments/assets/fcf9af5c-106b-4d33-8279-1f9b22374dbd)

![qq](https://github.com/user-attachments/assets/f129f5de-e185-401b-8de4-2e79d4f8b371)

![wx](https://github.com/user-attachments/assets/28933c70-c008-4fd5-924b-5189a700766e)

**Comment by wdssfff00** [comment]
补充qq扫码+web页面相关项目：[https://github.com/insoxin/qrjdc/tree/main](url)

**Comment by wdssfff00** [comment]
补充qq扫码+web页面相关项目：[https://github.com/insoxin/qrjdc/tree/main](https://github.com/insoxin/qrjdc/tree/main)

**Comment by icepage** [comment]
@wdssfff00  
1、十分理解您对于服务器安全的一些考虑，帐号密码明文配置十分敏感，有被人获取的风险。
2、也正如你所说，本项目主要是无人值守的全自动化方案，半自动化的扫码不会出现在这。
3、基于以上2点，如果(我是说如果)有未来的方向，我觉得更适合本项目的方式，是对密码脱敏的方式，同时打包成纯二进制。
4、上面说的只是交流意见，不构成做法，这种方式同时也增加了配置的复杂性。感谢您在这个注重快速的时代依然提出安全的建议。
