### ISSUE TITLE
启动失败了

### ISSUE THREAD

**Issue by AlonWangg** [icepage/AutoUpdateJdCookie#42]
部署在群辉docker 上启动失败了不知道是不是哪里有问题
![image](https://github.com/user-attachments/assets/ed2ad676-9440-4f90-9d49-6edf88a81d9d)

**Comment by icepage** [comment]
config.py 语法错误了，少了{

**Comment by AlonWangg** [comment]
> config.py 语法错误了，少了{

哈哈发现了谢谢您！ 登录必须要用带代理嘛我就在群辉本地地址不可以嘛！我代理配置是空的时候好像用不了

**Comment by icepage** [comment]
代理配置可以是空的，不能用是有什么报错吗？ @AlonWangg

**Comment by AlonWangg** [comment]
> 代理配置可以是空的，不能用是有什么报错吗？ @AlonWangg

![image](https://github.com/user-attachments/assets/a9558898-0f13-4c4c-8b71-f2aa9bb103e5)

**Comment by icepage** [comment]
你需要把config.py里的proxy的整段配置直接删除掉，就可以用了。这里我设置的默认值不合理，我做下兼容。 @AlonWangg

**Comment by AlonWangg** [comment]
> 你需要把config.py里的proxy的整段配置直接删除掉，就可以用了。这里我设置的默认值不合理，我做下兼容。 @AlonWangg

OK，我再测试下

**Comment by AlonWangg** [comment]
> 你需要把config.py里的proxy的整段配置直接删除掉，就可以用了。这里我设置的默认值不合理，我做下兼容。 @AlonWangg

@icepage 参照你这个删除了整个配置也用不了
![image](https://github.com/user-attachments/assets/457a3102-d11d-4970-b286-1d1eac9a7d7b)

**Comment by icepage** [comment]
改下配置，headless = True   @AlonWangg
