### ISSUE TITLE
感谢作者们的奉献。但是作为基础操作者有点看不懂部署步骤，pull了之后

### ISSUE THREAD

**Issue by corsgoo** [icepage/AutoUpdateJdCookie#45]
复制config_example.py, 重命名为config.py, 我们基于这个config.py运行程序;这个意思是pull之后按照第二步的“本地部署”来操作。但是前提是需要先“vim  /本地路径/config.py”，配置这个吧，我看步骤里面没写小白会看不懂说到底去哪里配置。

**Comment by icepage** [comment]
这边文档表述确实有问题，对新手不友好，我来修改下

**Comment by icepage** [comment]
文档已经更新
