### ISSUE TITLE
看了半天还是不清楚怎么配置，文章部署步骤有省略，望更新，，，pull之后不知道怎么操作了，config.py在哪里 main.py在哪里  sms是不是又要pull安装到docker？

### ISSUE THREAD

**Issue by corsgoo** [icepage/AutoUpdateJdCookie#46]
原谅我不是程序专业实在看半天不懂。。。

**Comment by corsgoo** [comment]
一。复制config_example.py, 重命名为config.py, 我们基于这个config.py运行程序;
按本地包部署文档里，关于config.py说明来配置，这个是自己去找个本地路径文件夹创建config.py？？？然后# 运行, 如果 config.py 在当前目录则不需要加文件映射
docker run -v /本地路径/config.py:/app/config.py icepage/aujc:latest？？
二。手动执行main.py。也是自己创建main.py  然后vim 该文件复制仓库的main.py内容进去再运行下面代码？
# 运行, 如果 config.py 在当前目录则不需要加文件映射
docker run -i -v /本地路径/config.py:/app/config.py icepage/aujc:latest python main.py？？？
三。SmsCodeWebhook 这个是要另外在docker部署吧？和这个主容器联动？

望作者可以理解新选手的疑惑，是否可以更新下详细的部署步骤，谢谢

**Comment by icepage** [comment]
这边文档表述确实有问题，对新手不友好，我来修改下

**Comment by icepage** [comment]
文档已做更新，问题我也答复一下，
1、下载本项目的config_example.py, 重命名为config.py，然后按照配置文档说明里改这个config.py
2、手动执行main.py。不用自己创建main.py，是运行docker镜像里的main.py，直接运行即可
3、 本项目提供了自定义webhook来实现自动化短信验证码识别的功能，自定义webhook需要客户自己实现，与主容器联动。其中SmsCodeWebhook是一个实现自定义webhook的参考项目。

**Comment by corsgoo** [comment]
docker run -i -v $PWD/config.py:/app/config.py icepage/aujc:latest python main.py

 $PWD是上传的config.py地址吧？这个地址是要ssh去docker目录下面创建一个AutoUpdateJdCookie文件夹，把config.py放进去然后运行这个代码？

**Comment by two1111** [comment]
我也遇到同样的问题，后面自己在Docker下新建了icepage文件夹，放入config.py和schedule_main.py两个文件（记得别放main.py文件），然后去ssh里直接运行那一段代码就好了（不用修改绝对路径），后面可以在容器里查到已经在运行了。

**Comment by gnosy2022** [comment]
同样的问题，我是在windows下。
