### ISSUE TITLE
docker跑完后就会自动退出容器

### ISSUE THREAD

**Issue by yuntian123456** [icepage/AutoUpdateJdCookie#54]
按照docker部署，运行docker run -v $PWD/config.py:/app/config.py icepage/aujc:latest，所有账号会依次立即更新一次，中间没有报错。
但是顺利更新完所有账号后，**容器就会自动退出。**
![image](https://github.com/user-attachments/assets/1e7523dc-e483-4b8e-8d7f-affb59db6e9f)
这样的话，定时任务就没有意义了。容器既已退出，定时时间到了也不会运行。
大家是这样的情况吗，还是说只有我的会运行完自动退出容器？

**Comment by nethawkhu** [comment]
你大概搞错了吧，这个docker并不是运行的时候就立即更新账号的啊，都是在 config 里面设置好定时的时间间隔，然后自动定时运行更新CK的。

**Comment by yuntian123456** [comment]
> 你大概搞错了吧，这个docker并不是运行的时候就立即更新账号的啊，都是在 config 里面设置好定时的时间间隔，然后自动定时运行更新CK的。

没搞错，我是docker一运行就开始更新账号，更新完了就自动退出了。 用了几天了，每次都是同样的情况，所以这几天都是手动运行docker来更新的。

**Comment by nethawkhu** [comment]
> > 你大概搞错了吧，这个docker并不是运行的时候就立即更新账号的啊，都是在 config 里面设置好定时的时间间隔，然后自动定时运行更新CK的。
> 
> 没搞错，我是docker一运行就开始更新账号，更新完了就自动退出了。 用了几天了，每次都是同样的情况，所以这几天都是手动运行docker来更新的。

你有修改 config 文件里面的更新时间设置吗？

而且我问过作者，他明确和我说不能在运行时候马上更新全部账号。具体可以看 #30 最后我的提问和作者的回答。

**Comment by yuntian123456** [comment]
> > > 你大概搞错了吧，这个docker并不是运行的时候就立即更新账号的啊，都是在 config 里面设置好定时的时间间隔，然后自动定时运行更新CK的。
> > 
> > 
> > 没搞错，我是docker一运行就开始更新账号，更新完了就自动退出了。 用了几天了，每次都是同样的情况，所以这几天都是手动运行docker来更新的。
> 
> 你有修改 config 文件里面的更新时间设置吗？
> 
> 而且我问过作者，他明确和我说不能在运行时候马上更新全部账号。具体可以看 #30 最后我的提问和作者的回答。

确实改了定时时间。。
我把定时时间改回和原版一样，结果还是一样的现象与😂🤣：【在运行时候马上更新全部账号，更新完毕后自动退出】

**Comment by jamesyoung233** [comment]
你运行的是手动模式，不是长期运行命令吧，马上更新的话更新那里应该是设了强制更新，再看一下配置文件的说明，作者介绍的很详细了，我也是docker运行的，没有问题

**Comment by yuntian123456** [comment]
找到原因了，末尾多了字段  python main.py
