### ISSUE TITLE
提供一个参考项目 https://github.com/zzhjj/svjdck

### ISSUE THREAD

**Issue by Alicil** [icepage/AutoUpdateJdCookie#6]

**Comment by Alicil** [comment]
有个问题就是，滑动窗口的验证码识别速度还能改吗？模拟人工   如果手动滑动，很少出现 图形验证码

**Comment by icepage** [comment]
速度目前不打算改，这个改速度的优先级较低，有时以这个速度也不会出图形。现在以主流程完全自动化为优先，后期再去攻克这块速度的问题

**Comment by icepage** [comment]
> 有个问题就是，滑动窗口的验证码识别速度还能改吗？模拟人工 如果手动滑动，很少出现 图形验证码

https://github.com/icepage/AutoUpdateJdCookie/commit/03464614a836414f725b3b41bd84f54bd22b1c58 ，参考svjdck项目作了换块的速度优化，希望可以帮助到你。
