### ISSUE TITLE
钉钉推送

### ISSUE THREAD

**Issue by linyi81953221** [icepage/AutoUpdateJdCookie#63]
send_info = {
    "send_wecom": [
    ],
    "send_webhook": [
    ],
    "send_dingtalk": [{"url":"https://oapi.dingtalk.com/robot/send?access_token=XXX","secret":"XXX"}
    ],
    "send_feishu": [
    ]
}
是这样表达吗？怎么推送不了呢

**Comment by deluo** [comment]
参考这个https://github.com/icepage/AutoUpdateJdCookie/issues/12#issuecomment-2207843243，作者的代码没解析secret这个参数

**Comment by icepage** [comment]
@linyi81953221 已做了钉钉加签的支持，感谢 @deluo 的提供

**Comment by linyi81953221** [comment]
@deluo @icepage 感谢感谢

**Comment by linyi81953221** [comment]
![Snipaste_2024-11-06_14-01-20](https://github.com/user-attachments/assets/b4e77710-80bc-4412-a30e-87d97f0f6c3d)
![Snipaste_2024-11-06_14-04-55](https://github.com/user-attachments/assets/bad4f93d-bbd8-4ff2-8a49-b984c82014c0)

是哪里还设置不对嘛。。。

**Comment by icepage** [comment]
拉了最新代码或镜像了吗？

**Comment by linyi81953221** [comment]
嗯嗯 那个拉取了

**Comment by linyi81953221** [comment]
拉取的最新镜像 docker

**Comment by linyi81953221** [comment]
config文件我看没更新就还用的原来的

**Comment by linyi81953221** [comment]
可以了！我重新把容器新建了一个！

**Comment by linyi81953221** [comment]
感谢！
