### ISSUE TITLE
滑块一直调整都是失败

### ISSUE THREAD

**Issue by uwhatsup** [icepage/AutoUpdateJdCookie#7]
# 滑块验证码的偏差, 如果一直滑过了, 或滑不到, 可以调节下
slide_difference = 6

以上参数1-15都调整了 还是出错，不知道是哪一步出问题了

![image](https://github.com/icepage/AutoUpdateJdCookie/assets/24759541/58c44f6f-9fde-406e-a13c-8a18b29d1b41)

**Comment by icepage** [comment]
重合后要么通过，要么出二次验证，理论上不会有其它情况了。

**Comment by uwhatsup** [comment]
手动滑就可以通过，不知道是不是速度太快还是什么原因导致

**Comment by uwhatsup** [comment]
https://blog.csdn.net/Thing_big/article/details/138340928

看到了一篇这样的文章 不知道会有有帮助

**Comment by icepage** [comment]
我这边没法复现你说的场景，不确定要怎么去做优化

**Comment by uwhatsup** [comment]
好吧  我先手动滑
