### ISSUE TITLE
大佬能否支持下2.11.3的青龙

### ISSUE THREAD

**Issue by laceeeeee** [icepage/AutoUpdateJdCookie#9]
测试2.15.6青龙正常使用。
京东都在2.11.3上使用，但会报错:
![微信截图_20240617145313](https://github.com/icepage/AutoUpdateJdCookie/assets/112396389/cd872396-1bf4-4a95-bd49-779cfee73392)

因为很菜，所以猜测是没有支持该版本的青龙所出现的报错。请大佬指点，谢谢~

**Comment by icepage** [comment]
https://github.com/icepage/AutoUpdateJdCookie/commit/508cd630bc17e23d26f45d07df2a16717fbf1f06，   原因是配置QL的url时末尾带了/，低版本的QL不支持，已做了兼容

**Comment by laceeeeee** [comment]
感谢大佬，已可以使用~~
